site_name: My Docs
theme: material

markdown_extensions:
  - admonition
  - codehilite

extra:
  palette:
    primary: 'blue'
    accent: 'light blue'

pages:
  - Home: index.md
  - Installing the Toolset: installing.md
  - About MkDocs: about-mkdocs.md
  - Using MkDocs: using.md
  - Command Line Reference: cmd-reference.md
  - Quick Markdown Reference: quick-md-reference.md

